### ISSUE TITLE
https://localhost:8443/canvas/ or https://localhost:8443/canvas/polls/?

### ISSUE THREAD

**Issue by raberaucht** [ericpalakovichcarr/django-facetools#1]
I'm following the tutorial on readthedocs - it's great by the way, thanks!

As described, I've created a facbook app and entered https://localhost:8443/canvas/ as canvas url.
Then, in urls.py, I changed

```
url(r'^polls/', include('polls.urls')),
```

to

```
url(r'^canvas/polls/', include('polls.urls')),
```

Now I'm getting this error message when I'm trying to access the app on https://apps.facebook.com/myapp/:

```
Page not found (404)
Request Method: GET
Request URL:    http://localhost:8443/canvas/

Using the URLconf defined in mysite.urls, Django tried these URL patterns, in this order:
1. ^canvas/polls/
2. ^admin/doc/
3. ^admin/
The current URL, canvas/, didn't match any of these.
```

A fix is to change the canvas url in the facebook app settings to https://localhost:8443/canvas/polls/ as far as I can see now.

**Comment by ericpalakovichcarr** [comment]
Hey, thanks for checking out django-facetools.  Actually, the problem is that you didn't add polls/ at the end of your facebook url.  Try this url instead:

https://apps.facebook.com/myapp/polls/

Where `myapp` should be the actual namespace of your facebook app.  You received the error message because we don't haven't the url path `/canvas/` to point to any views.

Let me know if that makes sense, and if the above fixed url makes the error page go away.

**Comment by raberaucht** [comment]
Yes, this makes sense - and it fixes the error.
And it even says so in the docs....

Thanks!

**Comment by ericpalakovichcarr** [comment]
No problem :)
